---
# tasks file for docker
- name: update package
  apt: update_cache=yes state=latest

- name: apt-get install these list
  apt: name={{ item }} state=latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker's official key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: latest

- name: command to set up the repository
  apt_repository: https://download.docker.com/linux/ubuntu bionic stable  
  
- name: update package
  apt: update_cache=yes state=latest

- name: apt-get install these list
  apt: name={{ item }} state=latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin 